USE rogers9879;

-- Create Tables
CREATE TABLE Landlord (
	LLID INT AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    PhoneNum VARCHAR(20) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PRIMARY KEY (LLID)
);

CREATE TABLE Property (
	PID INT NOT NULL AUTO_INCREMENT,
    LLID INT NOT NULL,
    Price NUMERIC(6, 2),
    Bed INT,
    Bath DOUBLE,
    PetsAllowed BOOLEAN,
    Address varchar(255),
    PRIMARY KEY (PID),
    CONSTRAINT fk_property_landlord FOREIGN KEY (LLID) REFERENCES Landlord(LLID)
);

CREATE TABLE Tenant (
	SSN VARCHAR(11) PRIMARY KEY NOT NULL,
    FName NVARCHAR(50) NOT NULL,
    MName NVARCHAR(50),
    LName NVARCHAR(50) NOT NULL,
    Budget DOUBLE,
    PhoneNum VARCHAR(20) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    BirthDate DATE
);

-- Create Relationships
CREATE TABLE LivesIn (
	SSN VARCHAR(11) NOT NULL,
    PID INT NOT NULL,
    PRIMARY KEY (SSN, PID),
    FOREIGN KEY (SSN) REFERENCES Tenant(SSN),
    FOREIGN KEY (PID) REFERENCES Property(PID)
);

CREATE TABLE LeasesFrom (
	SSN VARCHAR(11) NOT NULL,
    PID INT NOT NULL,
    PRIMARY KEY (SSN, PID),
    RentAgreement VARCHAR(255),
    FOREIGN KEY (SSN) REFERENCES Tenant(SSN),
    FOREIGN KEY (PID) REFERENCES Property(PID)
);